FROM node:16-alpine

WORKDIR '/app'

COPY package.json .

RUN npm install

COPY . .

CMD ["npm", "run", "start"]


#syntax to create with volumes
#docker run -p 3000:3000 -v /app/node_modules -v $(pwd):/app imageid